package net.luis.artifactory.handler.format;

import io.javalin.http.Context;
import net.luis.artifactory.Services;
import net.luis.artifactory.database.entity.FileEntity;
import net.luis.artifactory.database.entity.RepositoryEntity;
import net.luis.artifactory.repository.RepositoryType;
import net.luis.artifactory.storage.StoredBlob;
import net.luis.artifactory.util.Json;
import net.luis.artifactory.util.Versions;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import tools.jackson.databind.node.ObjectNode;

import java.io.InputStream;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static net.luis.artifactory.http.Requests.escapeXml;

/**
 * Maven 2 layout repository used by Maven and Gradle.<br>
 * <p>
 *     {@code maven-metadata.xml} files are always generated by the server from the stored artifacts,
 *     uploaded metadata files are accepted but ignored. Checksums ({@code .sha1}, {@code .md5}, {@code .sha256}, {@code .sha512})
 *     are computed on upload, uploaded checksum files are verified against the stored artifact.
 * </p>
 */
public class MavenHandler extends PathRepositoryHandler {
	
	private static final String METADATA = "maven-metadata.xml";
	private static final DateTimeFormatter LAST_UPDATED = DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(ZoneOffset.UTC);
	private static final Pattern SNAPSHOT_FILE = Pattern.compile("^(\\d{8}\\.\\d{6})-(\\d+)(?:-([^.]+))?\\.(.+)$");
	
	public MavenHandler(@NonNull Services services) {
		super(services);
	}
	
	@Override
	public @NonNull RepositoryType type() {
		return RepositoryType.MAVEN;
	}
	
	//region Coordinates
	
	/**
	 * Coordinates of an artifact file within the Maven 2 layout.<br>
	 */
	public record Coordinates(@NonNull String groupId, @NonNull String artifactId, @NonNull String version, @NonNull String fileName) {
		
		public @NonNull String packageName() {
			return this.groupId + ":" + this.artifactId;
		}
		
		public boolean isSnapshot() {
			return this.version.endsWith("-SNAPSHOT");
		}
	}
	
	public static @Nullable Coordinates parseCoordinates(@NonNull String path) {
		String[] segments = path.split("/");
		if (segments.length < 4) {
			return null;
		}
		String fileName = segments[segments.length - 1];
		String version = segments[segments.length - 2];
		String artifactId = segments[segments.length - 3];
		String groupId = String.join(".", Arrays.copyOfRange(segments, 0, segments.length - 3));
		
		boolean matches = fileName.startsWith(artifactId + "-" + version);
		if (!matches && version.endsWith("-SNAPSHOT")) {
			String base = version.substring(0, version.length() - "-SNAPSHOT".length());
			matches = fileName.startsWith(artifactId + "-" + base + "-");
		}
		return matches ? new Coordinates(groupId, artifactId, version, fileName) : null;
	}
	//endregion
	
	//region Virtual files
	@Override
	protected boolean serveVirtual(@NonNull Context ctx, @NonNull RepositoryEntity repository, @NonNull String path) throws Exception {
		String checksum = checksumExtension(path);
		String metadataPath = checksum == null ? path : stripExtension(path);
		if (fileName(metadataPath).equals(METADATA)) {
			String xml = this.generateMetadata(repository, metadataPath);
			if (xml == null) {
				return false;
			}
			serveGenerated(ctx, path, xml, "application/xml");
			return true;
		}
		
		FileEntity resolved = this.resolveNonUniqueSnapshot(repository, metadataPath);
		if (resolved != null) {
			if (checksum != null) {
				text(ctx, 200, digest(resolved, checksum));
			} else {
				this.services.artifacts().serve(ctx, resolved);
			}
			return true;
		}
		return false;
	}
	
	@Override
	protected boolean consumeVirtualUpload(@NonNull Context ctx, @NonNull RepositoryEntity repository, @NonNull String path) throws Exception {
		String metadataPath = checksumExtension(path) == null ? path : stripExtension(path);
		if (!fileName(metadataPath).equals(METADATA)) {
			return false;
		}
		try (InputStream input = ctx.bodyInputStream()) {
			input.transferTo(java.io.OutputStream.nullOutputStream());
		}
		ctx.status(201);
		return true;
	}
	
	private @Nullable String generateMetadata(@NonNull RepositoryEntity repository, @NonNull String metadataPath) throws Exception {
		int slash = metadataPath.lastIndexOf('/');
		if (slash < 0) {
			return null;
		}
		String directory = metadataPath.substring(0, slash);
		String[] segments = directory.split("/");
		
		if (segments.length >= 3 && segments[segments.length - 1].endsWith("-SNAPSHOT")) {
			String snapshot = this.generateSnapshotMetadata(repository, directory, segments);
			if (snapshot != null) {
				return snapshot;
			}
		}
		if (segments.length >= 2) {
			return this.generateVersionsMetadata(repository, segments);
		}
		return null;
	}
	
	private @Nullable String generateVersionsMetadata(@NonNull RepositoryEntity repository, String @NonNull [] segments) throws Exception {
		String artifactId = segments[segments.length - 1];
		String groupId = String.join(".", Arrays.copyOf(segments, segments.length - 1));
		List<FileEntity> files = this.services.artifacts().listByPackage(repository.name(), groupId + ":" + artifactId);
		if (files.isEmpty()) {
			return null;
		}
		
		TreeSet<String> versions = new TreeSet<>(Versions.MAVEN);
		Instant lastUpdated = Instant.EPOCH;
		for (FileEntity file : files) {
			if (file.version() != null) {
				versions.add(file.version());
			}
			if (file.createdAt().isAfter(lastUpdated)) {
				lastUpdated = file.createdAt();
			}
		}
		String release = versions.descendingSet().stream().filter(version -> !version.endsWith("-SNAPSHOT")).findFirst().orElse(null);
		
		StringBuilder xml = new StringBuilder();
		xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<metadata>\n");
		xml.append("  <groupId>").append(escapeXml(groupId)).append("</groupId>\n");
		xml.append("  <artifactId>").append(escapeXml(artifactId)).append("</artifactId>\n");
		xml.append("  <versioning>\n");
		xml.append("    <latest>").append(escapeXml(versions.last())).append("</latest>\n");
		if (release != null) {
			xml.append("    <release>").append(escapeXml(release)).append("</release>\n");
		}
		xml.append("    <versions>\n");
		for (String version : versions) {
			xml.append("      <version>").append(escapeXml(version)).append("</version>\n");
		}
		xml.append("    </versions>\n");
		xml.append("    <lastUpdated>").append(LAST_UPDATED.format(lastUpdated)).append("</lastUpdated>\n");
		xml.append("  </versioning>\n</metadata>\n");
		return xml.toString();
	}
	
	private record SnapshotFile(@NonNull String timestamp, int buildNumber, @Nullable String classifier, @NonNull String extension, @NonNull FileEntity file) {}
	
	private @NonNull List<SnapshotFile> snapshotFiles(@NonNull RepositoryEntity repository, @NonNull String directory, @NonNull String artifactId, @NonNull String baseVersion) throws Exception {
		List<SnapshotFile> result = new ArrayList<>();
		String prefix = artifactId + "-" + baseVersion + "-";
		for (FileEntity file : this.services.artifacts().list(repository.name(), directory + "/")) {
			String name = file.path().substring(directory.length() + 1);
			if (name.contains("/") || !name.startsWith(prefix) || checksumExtension(name) != null) {
				continue;
			}
			Matcher matcher = SNAPSHOT_FILE.matcher(name.substring(prefix.length()));
			if (matcher.matches()) {
				result.add(new SnapshotFile(matcher.group(1), Integer.parseInt(matcher.group(2)), matcher.group(3), matcher.group(4), file));
			}
		}
		return result;
	}
	
	private @Nullable String generateSnapshotMetadata(@NonNull RepositoryEntity repository, @NonNull String directory, String @NonNull [] segments) throws Exception {
		String version = segments[segments.length - 1];
		String artifactId = segments[segments.length - 2];
		String groupId = String.join(".", Arrays.copyOf(segments, segments.length - 2));
		String baseVersion = version.substring(0, version.length() - "-SNAPSHOT".length());
		
		List<FileEntity> all = this.services.artifacts().list(repository.name(), directory + "/");
		if (all.isEmpty()) {
			return null;
		}
		Instant lastUpdated = all.stream().map(FileEntity::createdAt).max(Comparator.naturalOrder()).orElse(Instant.now());
		List<SnapshotFile> files = this.snapshotFiles(repository, directory, artifactId, baseVersion);
		
		StringBuilder xml = new StringBuilder();
		xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<metadata modelVersion=\"1.1.0\">\n");
		xml.append("  <groupId>").append(escapeXml(groupId)).append("</groupId>\n");
		xml.append("  <artifactId>").append(escapeXml(artifactId)).append("</artifactId>\n");
		xml.append("  <version>").append(escapeXml(version)).append("</version>\n");
		xml.append("  <versioning>\n");
		
		if (files.isEmpty()) {
			xml.append("    <snapshot>\n      <localCopy>true</localCopy>\n    </snapshot>\n");
			xml.append("    <lastUpdated>").append(LAST_UPDATED.format(lastUpdated)).append("</lastUpdated>\n");
		} else {
			SnapshotFile latest = files.stream().max(Comparator.comparingInt(SnapshotFile::buildNumber).thenComparing(SnapshotFile::timestamp)).orElseThrow();
			xml.append("    <snapshot>\n");
			xml.append("      <timestamp>").append(latest.timestamp()).append("</timestamp>\n");
			xml.append("      <buildNumber>").append(latest.buildNumber()).append("</buildNumber>\n");
			xml.append("    </snapshot>\n");
			xml.append("    <lastUpdated>").append(LAST_UPDATED.format(lastUpdated)).append("</lastUpdated>\n");
			
			Map<String, SnapshotFile> newest = new TreeMap<>();
			for (SnapshotFile file : files) {
				String key = Objects.requireNonNullElse(file.classifier(), "") + ":" + file.extension();
				SnapshotFile current = newest.get(key);
				if (current == null || file.buildNumber() > current.buildNumber()) {
					newest.put(key, file);
				}
			}
			xml.append("    <snapshotVersions>\n");
			for (SnapshotFile file : newest.values()) {
				xml.append("      <snapshotVersion>\n");
				if (file.classifier() != null) {
					xml.append("        <classifier>").append(escapeXml(file.classifier())).append("</classifier>\n");
				}
				xml.append("        <extension>").append(escapeXml(file.extension())).append("</extension>\n");
				xml.append("        <value>").append(escapeXml(baseVersion + "-" + file.timestamp() + "-" + file.buildNumber())).append("</value>\n");
				xml.append("        <updated>").append(LAST_UPDATED.format(file.file().createdAt())).append("</updated>\n");
				xml.append("      </snapshotVersion>\n");
			}
			xml.append("    </snapshotVersions>\n");
		}
		xml.append("  </versioning>\n</metadata>\n");
		return xml.toString();
	}
	
	/**
	 * Resolves a non-unique snapshot file name (e.g. {@code toolkit-1.1.0-SNAPSHOT.jar}) to the latest timestamped snapshot.<br>
	 */
	private @Nullable FileEntity resolveNonUniqueSnapshot(@NonNull RepositoryEntity repository, @NonNull String path) throws Exception {
		Coordinates coordinates = parseCoordinates(path);
		if (coordinates == null || !coordinates.isSnapshot() || !coordinates.fileName().startsWith(coordinates.artifactId() + "-" + coordinates.version())) {
			return null;
		}
		String rest = coordinates.fileName().substring((coordinates.artifactId() + "-" + coordinates.version()).length());
		String classifier = null;
		String extension;
		if (rest.startsWith("-")) {
			int dot = rest.indexOf('.');
			if (dot < 0) {
				return null;
			}
			classifier = rest.substring(1, dot);
			extension = rest.substring(dot + 1);
		} else if (rest.startsWith(".")) {
			extension = rest.substring(1);
		} else {
			return null;
		}
		
		String directory = path.substring(0, path.lastIndexOf('/'));
		String baseVersion = coordinates.version().substring(0, coordinates.version().length() - "-SNAPSHOT".length());
		String finalClassifier = classifier;
		return this.snapshotFiles(repository, directory, coordinates.artifactId(), baseVersion).stream()
			.filter(file -> Objects.equals(file.classifier(), finalClassifier) && file.extension().equals(extension))
			.max(Comparator.comparingInt(SnapshotFile::buildNumber))
			.map(SnapshotFile::file)
			.orElse(null);
	}
	//endregion
	
	//region Upload
	@Override
	protected boolean isMutable(@NonNull String path) {
		Coordinates coordinates = parseCoordinates(path);
		return coordinates != null && coordinates.isSnapshot();
	}
	
	@Override
	protected @NonNull String conflictMessage(@NonNull String path) {
		Coordinates coordinates = parseCoordinates(path);
		if (coordinates == null) {
			return super.conflictMessage(path);
		}
		return "Version " + coordinates.version() + " already exists; releases are immutable";
	}
	
	@Override
	protected void store(@NonNull Context ctx, @NonNull RepositoryEntity repository, @NonNull String path, @NonNull StoredBlob blob, @Nullable String username) throws Exception {
		Coordinates coordinates = parseCoordinates(path);
		if (coordinates == null) {
			super.store(ctx, repository, path, blob, username);
			return;
		}
		
		this.services.artifacts().put(repository.name(), path, blob, contentType(path), coordinates.packageName(), coordinates.version(), null, username);
		if (this.services.packages().get(repository.name(), coordinates.packageName(), coordinates.version()) == null) {
			ObjectNode metadata = Json.object();
			metadata.put("groupId", coordinates.groupId());
			metadata.put("artifactId", coordinates.artifactId());
			this.services.packages().upsert(repository.name(), coordinates.packageName(), coordinates.version(), Json.write(metadata), username);
		}
	}
	
	@Override
	protected void afterDelete(@NonNull RepositoryEntity repository, @NonNull List<FileEntity> deleted) throws Exception {
		Set<List<String>> versions = new HashSet<>();
		for (FileEntity file : deleted) {
			if (file.packageName() != null && file.version() != null) {
				versions.add(List.of(file.packageName(), file.version()));
			}
		}
		for (List<String> version : versions) {
			if (this.services.artifacts().listByVersion(repository.name(), version.get(0), version.get(1)).isEmpty()) {
				this.services.packages().delete(repository.name(), version.get(0), version.get(1));
			}
		}
	}
	//endregion
}
