<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<TestLibVersion Condition="'$(TestLibVersion)' == ''">1.0.0</TestLibVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LArtifactory.TestLib" Version="$(TestLibVersion)" />
	</ItemGroup>

</Project>
